config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  resources :authors
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root to: "home#toppage"


  #diary

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/diary.rb
class Diary < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :age, :sex, :profile)
    end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: %i[ show edit update destroy ]

  # GET /diaries or /diaries.json
  def index

    @diaries = Diary.all
    yousosuu = @diaries.size

    for number in 1..yousosuu do
      this_diary =  @diaries[number-1]
      writer_id = this_diary.person_id
      
      if writer_id == nil
        writer_name = "<なし>"
      else
        writer = Person.find(writer_id)
        writer_name = writer.name
      end
      this_diary.update(writtenbyname:writer_name)
    end

    #p "==="
    #p @diaries

    @diaries = Diary.all
 
  end

  # GET /diaries/1 or /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
    @writers = Person.all
  end

  # POST /diaries or /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully created." }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1 or /diaries/1.json
  def update
    respond_to do |format|
      p "=============="  + diary_params.to_s + "=============="
      if @diary.update(diary_params)
        if @diary.person_id == nil
          writer_name = "<なし>"
        else
          writer_id = @diary.person_id
          writer_name = Person.find(writer_id).name
        end

        @diary.update(writtenbyname:writer_name)
        format.html { redirect_to diary_url(@diary), notice: "Diary was successfully updated." }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1 or /diaries/1.json
  def destroy
    @diary.destroy!

    respond_to do |format|
      format.html { redirect_to diaries_url, notice: "Diary was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def diary_params
      params.require(:diary).permit(:title, :text, :date, :person_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def toppage
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy!

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:name, :age, :sex, :profile)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong>Name:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= author.age %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= author.sex %>
  </p>

  <p>
    <strong>Profile:</strong>
    <%= author.profile %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :sex, style: "display: block" %>
    <%= form.check_box :sex %>
  </div>

  <div>
    <%= form.label :profile, style: "display: block" %>
    <%= form.text_area :profile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<% content_for :title, "Editing author" %>

<h1>Editing author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Authors" %>

<h1>Authors</h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to "Show this author", author %>
    </p>
  <% end %>
</div>

<%= link_to "New author", new_author_path %>

app/views/authors/new.html.erb
<% content_for :title, "New author" %>

<h1>New author</h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to "Back to authors", authors_path %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>

  <%= button_to "Destroy this author", @author, method: :delete %>
</div>

app/views/diaries/_diary.html.erb
<div id="<%= dom_id diary %>">
  <p>
    <strong>Title:</strong>
    <%= diary.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= diary.text %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= diary.date %>
  </p>

  <p>
    <strong>WrittenBy:</strong>
    <%= diary.writtenbyname %>
  </p>


</div>

app/views/diaries/_form.html.erb
<%= form_with(model: diary) do |form| %>
  <% if diary.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :writtenby, style: "display: block" %>
    <%= form.collection_select :person_id, @writers, :id, :name, include_blank: "<なし>" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<% content_for :title, "Editing diary" %>

<h1>Editing diary</h1>

<%= render "form", diary: @diary %>

<br>

<div>
  <%= link_to "Show this diary", @diary %> |
  <%= link_to "Back to diaries", diaries_path %>
</div>

app/views/diaries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Diaries" %>

<h1>Diaries</h1>

<div id="diaries">
  <% @diaries.each do |diary| %>


    <%= render diary %>
      <%= link_to "Show this diary", diary_path(diary) %>
    </p>
  <% end %>
</div>

<%= link_to "New diary", new_diary_path %>

app/views/diaries/new.html.erb
<% content_for :title, "New diary" %>

<h1>New diary</h1>

<%= render "form", diary: @diary %>

<br>

<div>
  <%= link_to "Back to diaries", diaries_path %>
</div>

app/views/diaries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @diary %>

<div>
  <%= link_to "Edit this diary", edit_diary_path(@diary) %> |
  <%= link_to "Back to diaries", diaries_path %>

  <%= button_to "Destroy this diary", @diary, method: :delete %>
</div>

app/views/home/toppage.html.erb
<h1>hello world</h1>
<div><a href="http://localhost:3000/diaries">diaries</a></div>
<div><a href="http://localhost:3000/people">peple</a></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Diary Watanabe 02" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :sex, style: "display: block" %>
    <%= form.check_box :sex %>
  </div>

  <div>
    <%= form.label :profile, style: "display: block" %>
    <%= form.text_area :profile %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>Name:</strong>
    <%= person.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= person.age %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= person.sex %>
  </p>

  <p>
    <strong>Profile:</strong>
    <%= person.profile %>
  </p>

</div>

app/views/people/edit.html.erb
<% content_for :title, "Editing person" %>

<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "People" %>

<h1>People</h1>

<div id="people">
  <% @people.each do |person| %>
    <%= render person %>
    <p>
      <%= link_to "Show this person", person %>
    </p>
  <% end %>
</div>

<%= link_to "New person", new_person_path %>

app/views/people/new.html.erb
<% content_for :title, "New person" %>

<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>